openapi: 3.0.0
info:
  title: Devoday API
  version: 1.0.0
  description: Documentação da API feita com Swagger

servers:
  - url: http://localhost:3003
    description: Servidor local

tags:
  - name: Auth
    description: Rotas de autenticação e cadastro

paths:
  /api/auth/cadastro:
    post:
      tags:
        - Auth
      summary: Cria um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Email inválido
                        path:
                          type: array
                          items:
                            type: string
                          example: ["email"]

components:
  schemas:
    Usuario:
      type: object
      properties:
        name:
          type: string
          example: "João"
        email:
          type: string
          format: email
          example: "joao@email.com"
        password:
          type: string
          format: password
          example: "senha123"
      required:
        - name
        - email
        - password
